# Generated by Django 3.2.9 on 2021-11-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20211116_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to='questions'),
        ),
        migrations.AddField(
            model_name='question',
            name='music',
            field=models.FileField(blank=True, upload_to='music_files/'),
        ),
    ]
