# Generated by Django 3.2.9 on 2021-11-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_category_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='time',
            field=models.IntegerField(default=1),
        ),
    ]
