# Generated by Django 3.2.9 on 2021-11-18 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_category_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Round',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='category',
            new_name='round',
        ),
    ]
