# Generated by Django 3.2.9 on 2021-11-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20211118_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscore',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
        migrations.DeleteModel(
            name='UserScore',
        ),
    ]
