# Generated by Django 3.2.9 on 2021-11-27 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ip',
        ),
    ]
