# Generated by Django 3.2.9 on 2021-11-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_auto_20211130_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sn',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
